name: Playwright TestNG Tests with Allure Report

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Install Maven dependencies
        run: |
          java -version
          mvn install -DskipTests

      - name: Run Playwright tests
        run: mvn clean test

      - name: Debug Allure Results
        if: always()
        run: |
          ls -la target/allure-results || echo "Directory not found"
          find target/allure-results -type f || echo "No files found in target/allure-results"

      - name: Check if gh-pages branch exists
        if: always()
        run: |
          if git ls-remote --heads origin gh-pages | grep gh-pages; then
            echo "gh-pages branch exists"
            echo "GH_PAGES_EXISTS=true" >> $GITHUB_ENV
          else
            echo "gh-pages branch does not exist"
            echo "GH_PAGES_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Load Allure history
        if: always() && env.GH_PAGES_EXISTS == 'true'
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.6
        if: always()
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          retention-days: 30
        continue-on-error: true

      - name: Publish Allure report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          keep_files: true
        continue-on-error: true

      - name: Print Allure Report URL
        if: always()
        run: |
          echo "Allure Report URL: https://Ruglon.github.io/test-framework-playwright/"